development:
  adapter: postgresql
  encoding: unicode
  database: budget_app
  pool: 5
  host: localhost
  username: postgres
  password: josh5091

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: postgres_user_name
  password: postgres_password

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
