development:
  adapter: postgresql
  encoding: unicode
  database: budget_app
  pool: 5
  host: localhost
  username: postgres
  password: josh5091

test:
  adapter: postgresql
  encoding: unicode
  database: budget_app
  pool: 5
  host: localhost
  username: postgres
  password: josh5091

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: postgresql
  database: budget_app_rj5r
  username: budget_app
  url: <%= ENV['DATABASE_URL'] %>
